// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poiskfile;

#nullable disable

namespace Poiskfile.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Poiskfile.MeteoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("aa11")
                        .HasColumnType("int");

                    b.Property<int?>("aa12")
                        .HasColumnType("int");

                    b.Property<string>("aa13")
                        .HasColumnType("longtext");

                    b.Property<string>("aa14")
                        .HasColumnType("longtext");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("dew1")
                        .HasColumnType("int");

                    b.Property<string>("dew2")
                        .HasColumnType("longtext");

                    b.Property<int>("station")
                        .HasColumnType("int");

                    b.Property<int?>("tmp1")
                        .HasColumnType("int");

                    b.Property<string>("tmp2")
                        .HasColumnType("longtext");

                    b.Property<int?>("wnd1")
                        .HasColumnType("int");

                    b.Property<int?>("wnd2")
                        .HasColumnType("int");

                    b.Property<string>("wnd3")
                        .HasColumnType("longtext");

                    b.Property<int?>("wnd4")
                        .HasColumnType("int");

                    b.Property<int?>("wnd5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MeteoDatas");
                });

            modelBuilder.Entity("Poiskfile.Meteostation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("admin_code")
                        .HasColumnType("int");

                    b.Property<string>("lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("station")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Meteostations");
                });
#pragma warning restore 612, 618
        }
    }
}
